// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiCObfTe9VLYzYEeRjiHlLKXSpCuhvG8s',
    appId: '1:913225380649:android:1813f4c2732284814e3d38',
    messagingSenderId: '913225380649',
    projectId: 'caraxes-app',
    storageBucket: 'caraxes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4viUOFU9r8KuV4w9X2ZPgm7UG45ZfGQw',
    appId: '1:913225380649:ios:099036022980ffa34e3d38',
    messagingSenderId: '913225380649',
    projectId: 'caraxes-app',
    storageBucket: 'caraxes-app.firebasestorage.app',
    iosBundleId: 'com.example.caraxesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4viUOFU9r8KuV4w9X2ZPgm7UG45ZfGQw',
    appId: '1:913225380649:ios:099036022980ffa34e3d38',
    messagingSenderId: '913225380649',
    projectId: 'caraxes-app',
    storageBucket: 'caraxes-app.firebasestorage.app',
    iosBundleId: 'com.example.caraxesApp',
  );
}
